name: 'Chromatic Deployment'
on:
  push:
    branches: [ main, develop ]  # mainとdevelopブランチへのプッシュのみ対象

jobs:
  chromatic-deployment:
    # コミットメッセージに'/chromatic'というキーワードが含まれる場合のみ実行
    if: contains(github.event.head_commit.message, '/chromatic')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: npm ci
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          exitZeroOnChanges: true  # 視覚的な変更があってもCIを失敗させない