name: 'Chromatic Deployment'
on:
  issue_comment:
    types: [created]

jobs:
  chromatic-deployment:
    # PRコメントで '/chromatic' と書かれた場合のみ実行
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/chromatic')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: npm ci
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}